apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nodeAffinity:
   required:
    nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
            - mango3 # change this dynamially
  hostPath:
    path: /tmp/mongodb-lsk # should create this directory

    # NOTE : if mongodb pod reports permission denied
    # Try below
    # sudo chown 1001:1001 /tmp/mongodb-lsk
    # sudo chmod 750 /tmp/mongodb-lsk
